get http://localhost:3000/todos/?status=TO%20DO

###
get http://localhost:3000/todos/?priority=HIGH

###

GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS

###

get http://localhost:3000/todos/?search_q=Play

###

//API2

get http://localhost:3000/todos/2/

###

//API3

post http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 11,
  "todo": "Finalize event music",
  "priority": "HIGH",
  "status": "TO DO"
}

###

//API4

put http://localhost:3000/todos/3/
Content-Type: application/json

{
  "status": "DONE"
}

###
put http://localhost:3000/todos/2/
Content-Type: application/json

{
  "priority": "HIGH"
}

###

put http://localhost:3000/todos/2/
Content-Type: application/json

{
  "todo": "Some task"
}

###

//API5

delete http://localhost:3000/todos/11/

###